spring.application.name=HogwartsDb

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

files.student.uploads.avatar=./files/student/uploads/avatar